name: vicuna_7b_fine_tuning_ds_lora_2n8u
hyperparameters:
  pretrained_model_name_or_path: /root/model
  deepspeed_config: ds_config_community.json
  model_mode: base
  use_pretrained_weights: true
  cache_dir: null
  lora_dropout: 0.05
  lora_r: 8
  lora_alpha: 16
data:
  data_path: /root/dataset/zh_honesty.json
  lazy_preprocess: false
records_per_epoch: 5344
min_validation_period:
  batches: 5344
searcher:
  name: single
  metric: perplexity
  max_length:
    epochs: 100
  smaller_is_better: true
resources:
  slots_per_trial: 8
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    - NCCL_SOCKET_IFNAME=bond
  image:
    gpu: registry.cn-beijing.aliyuncs.com/determined/environments:cuda-11.7-pytorch-1.13-deepspeed-0.9.2-gpu-0.22.1
bind_mounts:
  # - host_path: /home/nfs_data/models/vicuna/vicuna-13b/vicuna_13b_weights_v1.1
  - host_path: /home/nfs_data/models/vicuna/vicuna-7b/vicuna-7b
    container_path: /root/model
  - host_path: /home/nfs_data/dataset/MOSS_SFT
    container_path: /root/dataset
profiling:
  enabled: true
checkpoint_policy: best
checkpoint_storage:
  host_path: /home/nfs_data/vicuna_ft_MOSS_SFT_7b
  propagation: rprivate
  save_experiment_best: 0
  save_trial_best: 1
  save_trial_latest: 1
  storage_path: null
  type: shared_fs
entrypoint:
  - python3
  - -m
  - determined.launch.deepspeed
  - --trial
  - vicuna_trial:VicunaTrial